#!/usr/bin/env bash
###############################################################################
#  ZetaVPN — one-command installer
#
#  Fresh Debian/Ubuntu VPS, as root:
#     bash <(curl -fsSL https://raw.githubusercontent.com/<you>/zetavpn/main/install.sh)
#
#  Or from a local checkout:
#     sudo ./install.sh
#
#  Non-interactive example:
#     ZETA_DOMAIN=vpn.example.com ZETA_ADMIN_USERNAME=admin \
#     ZETA_ADMIN_PASSWORD=secret ./install.sh --yes
###############################################################################
set -euo pipefail

# Resolve where this script lives so we can find the rest of the repo.
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ZETA_HOME="${ZETA_HOME:-/opt/zetavpn}"
ZETA_REPO="${ZETA_REPO:-https://github.com/YOUR_GITHUB_USERNAME/zetavpn.git}"
ZETA_BRANCH="${ZETA_BRANCH:-main}"
PANEL_PORT="${PANEL_PORT:-2096}"
ASSUME_YES=0
if [ "${1:-}" = "--yes" ] || [ "${ZETA_YES:-}" = "1" ]; then ASSUME_YES=1; fi

# Source helpers from wherever they are (local checkout preferred).
if [ -f "${SELF_DIR}/scripts/common.sh" ]; then
  # shellcheck disable=SC1091
  . "${SELF_DIR}/scripts/common.sh"
  SOURCE_MODE="local"
else
  SOURCE_MODE="remote"
fi

# When bootstrapped via curl the helpers aren't local yet; define a minimal set.
if [ "$SOURCE_MODE" = "remote" ]; then
  C_RESET='\033[0m'; C_CYN='\033[36m'; C_GRN='\033[32m'; C_YEL='\033[33m'; C_RED='\033[31m'
  msg()  { printf "${C_CYN}::${C_RESET} %s\n" "$*"; }
  ok()   { printf "${C_GRN} ✓${C_RESET} %s\n" "$*"; }
  warn() { printf "${C_YEL} !${C_RESET} %s\n" "$*"; }
  die()  { printf "${C_RED} ✗${C_RESET} %s\n" "$*" >&2; exit 1; }
  need_root() { [ "$(id -u)" -eq 0 ] || die "Run as root."; }
  detect_os() { . /etc/os-release; OS_ID="$ID"; }
  banner() { printf "\n  Z E T A V P N   installer\n\n"; }
  apt_install() { DEBIAN_FRONTEND=noninteractive apt-get install -y "$@"; }
fi

need_root
banner
detect_os

# --------------------------------------------------------------------------- #
# 1. Base dependencies
# --------------------------------------------------------------------------- #
msg "Updating package index & installing base dependencies"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y >/dev/null 2>&1 || apt-get update -y
apt_install curl wget git unzip jq openssl ca-certificates \
            python3 python3-venv python3-pip vnstat >/dev/null 2>&1 || \
  apt_install curl wget git unzip jq openssl ca-certificates python3 python3-venv python3-pip
ok "Base dependencies installed"

# --------------------------------------------------------------------------- #
# 2. Fetch / copy the source into ZETA_HOME
# --------------------------------------------------------------------------- #
if [ -d "${SELF_DIR}/backend" ] && [ -d "${SELF_DIR}/frontend" ]; then
  if [ "${SELF_DIR}" != "${ZETA_HOME}" ]; then
    msg "Installing source from local checkout to ${ZETA_HOME}"
    mkdir -p "$ZETA_HOME"
    cp -a "${SELF_DIR}/." "${ZETA_HOME}/"
  fi
else
  if echo "$ZETA_REPO" | grep -q "YOUR_GITHUB_USERNAME"; then
    die "Set ZETA_REPO=https://github.com/<you>/zetavpn.git (or run install.sh from a checkout)."
  fi
  if [ -d "${ZETA_HOME}/.git" ]; then
    msg "Updating existing ZetaVPN checkout"
    git -C "$ZETA_HOME" fetch --depth 1 origin "$ZETA_BRANCH" && git -C "$ZETA_HOME" reset --hard "origin/${ZETA_BRANCH}"
  else
    msg "Cloning ${ZETA_REPO} (${ZETA_BRANCH})"
    rm -rf "$ZETA_HOME"
    git clone --depth 1 -b "$ZETA_BRANCH" "$ZETA_REPO" "$ZETA_HOME"
  fi
fi
cd "$ZETA_HOME"
chmod +x scripts/*.sh bin/zeta 2>/dev/null || true
# Re-source the full helpers now that they exist.
# shellcheck disable=SC1091
. "${ZETA_HOME}/scripts/common.sh"
ok "Source ready in ${ZETA_HOME}"

# --------------------------------------------------------------------------- #
# 3. Python environment
# --------------------------------------------------------------------------- #
msg "Creating Python virtual environment"
python3 -m venv "${ZETA_HOME}/venv"
"${ZETA_HOME}/venv/bin/pip" install --quiet --upgrade pip wheel
"${ZETA_HOME}/venv/bin/pip" install --quiet -r "${ZETA_HOME}/backend/requirements.txt"
ok "Panel dependencies installed"

mkdir -p "$ZETA_DATA" "$ZETA_CERT_DIR"

# --------------------------------------------------------------------------- #
# 4. Generate .env (first run only)
# --------------------------------------------------------------------------- #
SERVER_IP="$(server_ip)"
if [ ! -f "$ZETA_ENV" ]; then
  SECRET="$(openssl rand -hex 32)"
  WEBPATH="${ZETA_WEB_BASE_PATH:-zeta-$(openssl rand -hex 4)}"
  ADMIN_USER="${ZETA_ADMIN_USERNAME:-admin}"
  ADMIN_PASS="${ZETA_ADMIN_PASSWORD:-$(openssl rand -base64 12 | tr -dc 'A-Za-z0-9' | head -c 14)}"
  cat > "$ZETA_ENV" <<ENV
# ZetaVPN environment — generated by install.sh
ZETA_SECRET_KEY=${SECRET}
ZETA_PORT=${PANEL_PORT}
ZETA_WEB_BASE_PATH=${WEBPATH}
ZETA_SERVER_ADDRESS=${SERVER_IP}
ZETA_SERVER_DOMAIN=${ZETA_DOMAIN:-}
ZETA_ADMIN_USERNAME=${ADMIN_USER}
ZETA_ADMIN_PASSWORD=${ADMIN_PASS}
ENV
  chmod 600 "$ZETA_ENV"
  ok "Configuration written to ${ZETA_ENV}"
else
  warn "Existing ${ZETA_ENV} kept (delete it to regenerate credentials)."
fi
# shellcheck disable=SC1091
set -a; . "$ZETA_ENV"; set +a

# --------------------------------------------------------------------------- #
# 5. Install cores + system components
# --------------------------------------------------------------------------- #
bash "${ZETA_HOME}/scripts/install_xray.sh"
bash "${ZETA_HOME}/scripts/install_singbox.sh"
bash "${ZETA_HOME}/scripts/install_ssh_stack.sh"
bash "${ZETA_HOME}/scripts/tune_bbr.sh"

if [ -n "${ZETA_DOMAIN:-}" ]; then
  ZETA_DOMAIN="$ZETA_DOMAIN" bash "${ZETA_HOME}/scripts/install_ssl.sh" || warn "SSL step failed; continuing without a cert."
fi
PANEL_PORT="$PANEL_PORT" ZETA_DOMAIN="${ZETA_DOMAIN:-}" bash "${ZETA_HOME}/scripts/install_nginx.sh"
PANEL_PORT="$PANEL_PORT" bash "${ZETA_HOME}/scripts/firewall.sh" || warn "Firewall step reported problems."

# --------------------------------------------------------------------------- #
# 6. systemd units + CLI
# --------------------------------------------------------------------------- #
msg "Installing systemd services"
install -m 0644 "${ZETA_HOME}/systemd/"zeta-*.service /etc/systemd/system/
install -m 0755 "${ZETA_HOME}/bin/zeta" /usr/local/bin/zeta
systemctl daemon-reload
systemctl enable --now zeta-panel.service
systemctl enable --now zeta-xray.service
systemctl enable zeta-singbox.service >/dev/null 2>&1 || true
systemctl enable --now zeta-ws.service
ok "Services installed and started"

# Install the cron helper that expires SSH accounts.
( crontab -l 2>/dev/null | grep -v 'zeta expire-check'; \
  echo "*/15 * * * * /usr/local/bin/zeta expire-check >/dev/null 2>&1" ) | crontab - 2>/dev/null || true

# --------------------------------------------------------------------------- #
# 7. Summary
# --------------------------------------------------------------------------- #
BASE="/${ZETA_WEB_BASE_PATH:-}"
ADMIN_USER_SHOW="${ZETA_ADMIN_USERNAME:-admin}"
ADMIN_PASS_SHOW="${ZETA_ADMIN_PASSWORD:-<see ${ZETA_DATA}/initial_admin.txt>}"
ACCESS_HOST="${ZETA_DOMAIN:-$SERVER_IP}"
if [ -n "${ZETA_DOMAIN:-}" ] && [ -f "${ZETA_CERT_DIR}/fullchain.pem" ]; then
  PANEL_URL="https://${ACCESS_HOST}${BASE}/"
else
  PANEL_URL="http://${SERVER_IP}:${PANEL_PORT}${BASE}/"
fi

cat <<SUMMARY

$(ok "ZetaVPN installation complete!")

  ┌───────────────────────────────────────────────
  │  Panel URL : ${PANEL_URL}
  │  Username  : ${ADMIN_USER_SHOW}
  │  Password  : ${ADMIN_PASS_SHOW}
  ├───────────────────────────────────────────────
  │  CLI menu  : run  'zeta'
  │  SSH ports : 22 · 149/143 (dropbear) · 445 (SSL) · 8880 (WS)
  │  Config    : ${ZETA_ENV}
  └───────────────────────────────────────────────

  Next: set your domain under Settings, add inbounds, create clients.
SUMMARY
